web: &app_base
  build: .
  command: rails s -p 3000 -b 0.0.0.0
  ports:
    - "3000:3000"
  volumes:
    - .:/srv/app
    - ./log:/srv/app/log
  links:
    - postgres
  environment:
    DB_HOST: "postgres"
    DB_USER: "postgres"
    DB_PASS: "password"

postgres:
  image: postgres
  ports:
    - "5432"
