development: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USER'] || "root" %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: seed_rails_development

test:
  <<: *default
  database: seed_rails_test

production:
  <<: *default
  database: seed_rails_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # url: <%= ENV['DATABASE_URL'] %>
