# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 455da3b549e56a941e8f39ac9835c91325a9b78581dc13ed1be1cec98c01cee4a04a750ef51179b7c52b770f3c85ebc25af7a6303afa6d4f0d55c9654898d46e

test:
  secret_key_base: 7d87354fbbe1a9d2b1bda22cf93a826636262c35e48a5276aa993eb716c3a0f9e3be64b6481078eb9ea5972b43244f18dc9f10cff4b0551b37cc62a690b80ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
